site_name: APIstry
site_url: https://docs.contract-as-a-service.net
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.expand
#    - navigation.sections
    - navigation.tracking
#    - navigation.top
#    - navigation.tabs
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
  font:
    text: Inter
    code: Roboto Mono

extra_css:
  - css/custom.css
  - css/home.css

extra_javascript:
  - js/custom.js

extra:
  generator: false

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Problem & Motivation: getting-started/problem.md
    - Core Concepts: getting-started/core-concept.md
  - Design Guide:
    - Contract Design: design-guide/contract-design.md
    - Business Logic: design-guide/business-logic.md
    - Patterns: design-guide/patterns.md
    - Reference & Examples: design-guide/reference-examples.md
  - Architecture & Operations:
    - Architecture & Runtime: architecture-operations/architecture.md
    - Adoption: architecture-operations/adoption.md
  - Implementation:
    - Getting Started: implementation/README.md
    - Collection Auto-Creation: implementation/collection-auto-creation.md
