site_name: APIstry
site_url: https://www.apistry.net
use_directory_urls: true

nav:
  - "<- Home": https://www.apitapestry.net
  - APIstry: apistry.md
  - Overview: README.md
  - GETTING STARTED:
      - Getting Started: implementation
      - Collection Auto-Creation: implementation/collection-auto-creation.md
      - Concepts: concepts.md
      - Installation: installation.md
      - Server Start: quickstart.md
      - Features: features.md
  - GUIDES:
      - APIstry CLI: apistrycli.md
  - REFERENCE:
      - Placeholder: placeholder.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.expand
    - navigation.tracking
#    - navigation.sections
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
  font:
    text: Inter
    code: Roboto Mono

extra_css:
  - css/custom.css
  - css/home.css
  - css/layout.css
