site_name: APIstry
site_url: https://www.apistry.net
use_directory_urls: true

nav:
  - "<- Home": https://www.apitapestry.net
  - APIstry: apistry.md
  - Overview: README.md
  - GETTING STARTED:
      - Concepts: concepts.md
      - Features: features.md
      - Installation: installation.md
      - MongoDB: mongodb.md
      - Start Server: start-server.md
      - Testing: testing.md
  - GUIDES:
      - APIstry CLI: apistry-cli.md
  - REFERENCE:
      - OpenApi Design: openapi-design.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.expand
    - navigation.tracking
#    - navigation.sections
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
  font:
    text: Inter
    code: Roboto Mono

extra_css:
  - css/custom.css
  - css/home.css
  - css/layout.css
