site_name: APIstry
site_url: https://www.apistry.net
use_directory_urls: true

copyright: 'Â©2025 API Tapestry. All rights reserved.'

nav:
  - "<- Home": https://www.apitapestry.net
  - APIstry: https://www.apitapestry.net/apistry
  - Overview: README.md
  - GETTING STARTED:
      - Concepts: concepts.md
      - Features: features.md
      - Installation: installation.md
      - MongoDB: mongodb.md
      - Start Server: start-server.md
      - Testing: testing.md
  - GUIDES:
      - APIstry CLI: apistry-cli.md
  - REFERENCE:
      - OpenApi Design: openapi-design.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.expand
    - navigation.tracking
    - navigation.footer
#    - navigation.sections
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
  font:
    text: Inter
    code: Roboto Mono

extra_css:
  - css/extra.css
#
##HIDE SEARCH BAR (desktop + mobile)
#.md-header__option.md-search {
#  display: none !important;
#}
#
#.md-search {
#  display: none !important;
#}
